theme: jekyll-theme-cayman
title: Mod Tanks
description: Wee Tanks with mod support via BepInEx and useful mods for messing around with the game Wee Tanks. 
show_downloads: true
download_url: https://github.com/nonperforming/modtanks/releases
