theme: jekyll-theme-cayman
title: Mod Tanks
description: Wee Tanks with mod support and useful mods for messing around with the game Wee Tanks via BepInEx. 
show_downloads: false
download_url: https://github.com/nonperforming/modtanks/releases
